function(add_warnings target)
    if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.15")
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND
            CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC"))
            target_compile_options("${target}" PRIVATE /W4)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GCC" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            target_compile_options("${target}"  PRIVATE -Wall -Wextra -Wpedantic)
        endif()
    else()
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            target_compile_options("${target}"  PRIVATE /W4)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GCC" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            target_compile_options("${target}"  PRIVATE -Wall -Wextra -Wpedantic)
        endif()
    endif()
endfunction()

function(add_werror target)
    if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.15")
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND
            CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC"))
            target_compile_options("${target}" PRIVATE /Wx)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GCC" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            target_compile_options("${target}"  PRIVATE -Werror)
        endif()
    else()
        if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            target_compile_options("${target}"  PRIVATE /W4)
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GCC" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            target_compile_options("${target}"  PRIVATE -Werror)
        endif()
    endif()
endfunction()

